# Site settings
title: Pream Totaram
email: pream@preamtotaram.com
description: > 
 This is my personal site, and a view of what I have done. 
 When I figure something out, or learn how to do something, 
 I will generally post about it for use as a reference
 The repo for this site is public on Github.  
 Feel free to look at it and review the code.
 I am always looking to improve my skillset
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://preamtotaram.com" # the base hostname & protocol for your site
twitter_username: ptotaram
github_username:  ptotaram
phone: (914) 689-1237

# Build settings
markdown: redcarpet
