# Site settings
title: Pream Totaram
email: pream0526@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://preamtotaram.com" # the base hostname & protocol for your site
twitter_username: ptotaram
github_username:  ptotaram

# Build settings
markdown: redcarpet
