# Site settings
title: Pream Totaram
email: pream@preamtotaram.com
description: > 
 I am a freelance web developer. Feel free to reach out to me if you need assistance on a project. I also love working with and refactoring legacy code.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://preamtotaram.com" # the base hostname & protocol for your site
twitter_username: ptotaram
github_username:  ptotaram
phone: (347) 709-1179


theme: jekyll-theme-cayman